channels:
- conda-forge
dependencies:
- python=3.9.12
- pip<=21.2.4
- pip:
  - mlflow
  - cloudpickle==2.0.0
  - lz4==3.1.3
  - psutil==5.8.0
  - scikit-learn==1.0.2
  - typing-extensions==4.4.0
name: mlflow-env
